### ISSUE TITLE
Add XHRLoader fix

### ISSUE THREAD

**Issue by richtr** [cx20/gltf-test#1]
I'll just leave this here as it is important for making `glTF-Embedded` demos work on Safari in OS X and iOS.

Please build three.js latest dev branch file from this PR: https://github.com/mrdoob/three.js/pull/9823.

Also, it would then be good to update the results in the README. `glTF-Embedded` demos should then work on Safari.

**Comment by cx20** [comment]
@richtr I build three.js latest dev branch and tried new GLTF Loader.

I confirmed that `glTF-Embedded` demos work on Safari in OS X and iOS.

I updated the results in the README. :-)

**Comment by richtr** [comment]
Awesome. Thanks!
