### ISSUE TITLE
PlayCanvas viewer needs to be updated to new animation component

### ISSUE THREAD

**Issue by willeastcott** [cx20/gltf-test#125]
Currently, the viewer in this repo is failing the InterpolationTest test. This is because it is based on the `animation` component. It needs to be updated to the `anim` component, which is now used by the official PlayCanvas viewer:

https://github.com/playcanvas/playcanvas-viewer/pull/17

Then, InterpolationTest will pass successfully.

**Comment by cx20** [comment]
@willeastcott Thanks to your advice, I've confirmed that the Animation in InterpolationTest works.
However, the animation doesn't seem to start unless I click on it. Perhaps I'm having a usage problem, but I haven't been able to investigate it. Can you give me additional advice?

[PlayCanvas v1.33.0-dev + InterpolationTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/b401fe5d13a76ec8b354096ed3055531ac978847/examples/playcanvas/index.html?category=tutorialModels&model=InterpolationTest&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/88729470-f37ec280-d16e-11ea-896d-838a6cfc172a.png)

**Comment by willeastcott** [comment]
Thanks for trying to fix this so quickly! @slimbuck can provide you some advice tomorrow (since he was the one who fixed this in our viewer today). We're hoping we can flip all tests to pass (except for extension tests) by tomorrow. 😄

**Comment by slimbuck** [comment]
Hi @cx20,

The PC viewer goes to some trouble to only render frames when necessary so you can leave the viewer tab open without it killing your GPU/battery. :)

Just set autoRender to true at https://github.com/cx20/gltf-test/blob/master/examples/playcanvas/index.js#L126

Thanks!

**Comment by slimbuck** [comment]
I went ahead and submitted a PR https://github.com/cx20/gltf-test/pull/129

**Comment by willeastcott** [comment]
Also, you might want to switch to an official release version for the engine. v1.32.3 fixes the Texture Settings Test:

![image](https://user-images.githubusercontent.com/697563/88777570-452f4900-d17f-11ea-9e3e-f89c32614c1d.png)

**Comment by cx20** [comment]
I confirmed that the PR I received solved the problem.
