### ISSUE TITLE
glTF 2.0 models does not displyed by Three.js

### ISSUE THREAD

**Issue by cx20** [cx20/gltf-test#14]
I am preparing examples of various libraries corresponding to glTF 2.0.
However, glTF 2.0 models does not displyed by Three.js
https://github.com/cx20/gltf-test/tree/2.0
ex) Boom Box
https://cdn.rawgit.com/cx20/gltf-test/9ba70f0f946967c0cc0759173d4567a3f16c8469/examples/threejs/index.html?category=tutorialModels&model=BoomBox&scale=1&type=glTF

I think that usage is probably wrong. However, the point of the problem is not known :(

## The following are the points I tried this time.

1. Copied following libraries to my 2.0 branch

> https://github.com/donmccurdy/three.js/blob/feat-gltf-pbr/build/three.js
> https://github.com/donmccurdy/three.js/blob/feat-gltf-pbr/examples/js/loaders/GLTF2Loader.js

2. Changed index.html for 2.0

> Changed from GLTFLoader.js to GLTF2Loader.js.
> https://github.com/cx20/gltf-test/blob/2.0/examples/threejs/index.html#L19

3. Changed index.js for 2.0

> Changed from THREE.GLTFLoader to THREE.GLTF2Loader
> https://github.com/cx20/gltf-test/blob/2.0/examples/threejs/index.js#L42
> https://github.com/cx20/gltf-test/blob/2.0/examples/threejs/index.js#L95

@donmccurdy Please advise me what is wrong.
/cc @takahirox

**Comment by cx20** [comment]
I copied the following library to my 2.0 branch and the PBR model is now displayed.

> https://github.com/takahirox/three.js/blob/GLTF2tmp/build/three.js
> https://github.com/takahirox/three.js/blob/GLTF2tmp/examples/js/loaders/GLTF2Loader.js

I think that this library is probably WIP, I will update again when a new version comes out.

**Comment by donmccurdy** [comment]
Yes, we're WIP and a little ways from having anything stable yet. Working on metallic/roughness first and specular/gloss will need to be implemented later.

**Comment by donmccurdy** [comment]
@cx20 would you mind reverting to the stable version of GLTF2Loader? There are some other issues to iron out (see #16) and I'd prefer to keep track of three.js dev instead of my PBR branch. Thanks!
