### ISSUE TITLE
glTF 2.0 models does not displyed by xeogl

### ISSUE THREAD

**Issue by cx20** [cx20/gltf-test#15]
I am preparing examples of various libraries corresponding to glTF 2.0.
I copied following libraries to my 2.0 branch

> https://github.com/xeolabs/xeogl/blob/master/build/xeogl.js (2017.02.23)

However, glTF 2.0 models does not displyed by xeogl
https://github.com/cx20/gltf-test/tree/2.0
ex) Boom Box
https://cdn.rawgit.com/cx20/gltf-test/adfa139d3d7f71fdad820d6fad98c7d4f815a82a/examples/xeogl/index.html?category=tutorialModels&model=BoomBox&scale=1&type=glTF

The following error will be displayed on the console.
```js
Uncaught TypeError: Cannot read property 'description' of undefined
    at Function.value (xeogl.js:31783)
    at Function.value (xeogl.js:31799)
    at Object.value (xeogl.js:32364)
    at Object.value (xeogl.js:31410)
    at xeogl.js:31504
    at xeogl.js:31458
    at XMLHttpRequest.jsonfile.onreadystatechange (xeogl.js:31441)
```

@xeolabs Please advise me what is wrong.

**Comment by xeolabs** [comment]
I know what the xeogl issue is with the boom box, I'll fix it tomorrow.

**Comment by cx20** [comment]
@xeolabs Currently BoomBox will be displayed, so close this Issue.
![image](https://user-images.githubusercontent.com/1833979/30240925-ab28c772-95b4-11e7-880b-beb3d5dc4961.png)
