### ISSUE TITLE
consider glb with MaterialsCommon

### ISSUE THREAD

**Issue by andreasplesch** [cx20/gltf-test#17]
I noticed that some engines do not fully support binary glTF (v.1.0) which use the KHR extension, including x3dom.  These can be generated with the --kmc.enable switch for gltf-pipeline from the glTF-MaterialsCommon files. Consider adding tests for such binary glTF.
I did this for the CesiumMilkTruck and may put together a PR. Generated .glb files could be added incrementally.

**Comment by andreasplesch** [comment]
I went ahead and created binary glTF using KHR extension:

https://github.com/andreasplesch/gltf-test/blob/Binary-MC/index.html
https://rawgit.com/andreasplesch/gltf-test/Binary-MC/index.html

Feel free to pull in this branch if there is interest.

also see:
https://github.com/KhronosGroup/glTF-Sample-Models/issues/109

**Comment by cx20** [comment]
@andreasplesch Thank you for a suggestion.
The sample model used in this repository is copied from Khronos's glTF-Sample-Models and used.
To the best of my knowledge, At the moment the following samples are not present in the Khronos repository.

glTF-Binary-MaterialsCommon
glTF-Embedded-MaterialsCommon

I think that it is desirable to do more tests, but creating a sample of myriad patterns will be a painful problem as the repository grows bloated. Once samples are added to the Khronos repository, I would like to add a test case to this repository as well.

**Comment by andreasplesch** [comment]
I understand and opened an issue https://github.com/KhronosGroup/glTF-Sample-Models/issues/109 .
In the mean time I will keep my branches around and stable.
I do think binary gltf as a single file, compact format will be especially important and heard that MS uses it for Paint3D.
