### ISSUE TITLE
Merge 2.0 branch?

### ISSUE THREAD

**Issue by pjcozzi** [cx20/gltf-test#18]
Given all the glTF 2.0 momentum and to encourage even more of it, is the 2.0 branch ready to be merged to master?  If you still want to track 1.0 implementation status, you could make separate pages like we have for the 1.0 and 2.0 spec.

Thanks again for your awesome work here!

**Comment by cx20** [comment]
@pjcozzi  Thanks for the advice. I merged 2.0 branch into master, now.

**Comment by pjcozzi** [comment]
Awesome, thanks @cx20!
