### ISSUE TITLE
Using ToyCar's built-in camera in Babylon.js, the model is not displayed correctly

### ISSUE THREAD

**Issue by cx20** [cx20/gltf-test#236]
I have tried to display the official Khronos sample ToyCar in Babylon.js.
However, with the ToyCar's built-in camera, the display will be rough.

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/ToyCar

[Babylonjs + ToyCar result:](https://rawcdn.githack.com/cx20/gltf-test/e2f263ccef493ffa21315d942adbc72246baf3c8/examples/babylonjs/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF&camera=Camera003)
![image](https://user-images.githubusercontent.com/1833979/100931445-e2cfc600-352d-11eb-8306-249a3b85ec33.png)

Probably due to adjusting minZ(near) for VC.gltf.
https://github.com/cx20/gltf-test/blob/e2f263ccef493ffa21315d942adbc72246baf3c8/examples/babylonjs/index.js#L94

**Comment by cx20** [comment]
I made sure that the display of ToyCar's built-in models is improved, which will be improved by eliminating the scale adjustment and minZ(near) adjustment in the mesh.

[Babylon.js + ToyCar latest result:](https://rawcdn.githack.com/cx20/gltf-test/82d6d1decfe678c767232afc9d7da87d14d7644a/examples/babylonjs/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/100933043-1875ae80-3530-11eb-9711-ee547ce27455.png)

**Comment by cx20** [comment]
However, with this fix, VC.gltf's built-in camera will not be displayed correctly in Babylon.js.
There is a feeling of difference in the characteristics of the camera, but it needs to be confirmed.

[Babylon.js + VC.gltf + camera1 result:](https://rawcdn.githack.com/cx20/gltf-test/82d6d1decfe678c767232afc9d7da87d14d7644a/examples/babylonjs/index.html?category=sampleModels&model=VC&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/100933771-2b3cb300-3531-11eb-8376-d3f1434b0546.png)

[Three.js + VC.gltf + camera1 result:](https://rawcdn.githack.com/cx20/gltf-test/82d6d1decfe678c767232afc9d7da87d14d7644a/examples/threejs/index.html?category=sampleModels&model=VC&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/100934230-d0578b80-3531-11eb-8396-4c6e0d7425d7.png)

**Comment by cx20** [comment]
I'm not sure why, but when I try to adjust the display size of the model at the position of the Camera, it seems that a blue triangle appears flickering.

```javascript
camera.minZ /= 1000; // TODO: If near is 1, the model is missing, so adjusted
camera.setPosition(new BABYLON.Vector3(0 / scale, 3 / scale, -5 / scale));
````

![image](https://user-images.githubusercontent.com/1833979/101026183-ee68ce80-35b9-11eb-9b1d-dfcee6f7455c.png)

**Comment by bghgary** [comment]
I'm investigating this.

**Comment by bghgary** [comment]
It looks like the zfar value in the model is 2, which is much too small.

**Comment by cx20** [comment]
@bghgary Thank you for investigating.

After some trial and error, I'm not sure if that's the right way to do it, but I've found that the code below can reduce the flicker to some extent.

https://github.com/cx20/gltf-test/blob/1d083482087b6f7931b686d50454f5a920929c4b/examples/babylonjs/index.js#L109-L111

I also checked the model. Certainly, the `zNear` / `zFar` values of `VC.gltf` and `ToyCars.gltf`'s built-in cameras are extreme.

|Model|Camera settings|Remarks|
|:----:|:-----:|:-----:|
|VC.gltf|![image](https://user-images.githubusercontent.com/1833979/101094996-9c976700-3600-11eb-9565-ebed857807d5.png)|zNear `1` is too big|
|ToyCar.gltf|![image](https://user-images.githubusercontent.com/1833979/101095022-a751fc00-3600-11eb-812a-7952b89cbfad.png)|zFar `2` is too small|

**Comment by bghgary** [comment]
@cx20 We've merged a [PR](https://github.com/BabylonJS/Babylon.js/pull/9553) that will fix the zFar issue. If you are creating a skybox manually (not through scene.createDefaultSkybox), then make sure you set `ignoreCameraMaxZ` to true on the skybox mesh. Let me know if it works for you.

**Comment by cx20** [comment]
@bghgary Thank you for improving the library. I have checked the latest version of Babylon.js and glTF Loader for improved camera support.
I have confirmed that the latest version of the library has `ignoreCameraMaxZ` set in the skybox and displays correctly.
And I confirmed that the flickering was improved without adjusting `camera.maxZ`.

|Model|Babylon.js v5.0.0-alpha.1|Babylon.js v5.0.0-alpha.3|
|:----:|:----:|:----:|
|ToyCar|[![image](https://user-images.githubusercontent.com/1833979/101813529-2c3c9880-3b60-11eb-98a8-935e808be321.png)](https://rawcdn.githack.com/cx20/gltf-test/82d6d1decfe678c767232afc9d7da87d14d7644a/examples/babylonjs/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)|[![image](https://user-images.githubusercontent.com/1833979/101813554-32327980-3b60-11eb-8d21-1d8962dbf335.png)](https://rawcdn.githack.com/cx20/gltf-test/4475ae85a81a0b5f13a9f0522183842faaf9d1c0/examples/babylonjs/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)|

BTW, I need to adjust the `camera.minZ` for the `VC` models. Is this unavoidable due to the characteristics of the camera?

**Comment by bghgary** [comment]
> BTW, I need to adjust the camera.minZ for the VC models. Is this unavoidable due to the characteristics of the camera?

There is no way to ignore minZ besides explicitly changing it to another value. I think we should probably change the model. Having a minZ of 1 doesn't make much sense.

**Comment by cx20** [comment]
@bghgary I understand. Thank you for teaching me. The issue has been resolved and is closed.
