### ISSUE TITLE
Should provide a UI to change sample settings

### ISSUE THREAD

**Issue by cx20** [cx20/gltf-test#25]
Currently, the code for rotating the model is hard-coded.
It is preferable that this processing can be set by the control panel such as dat.gui.js.

**Comment by emackey** [comment]
Where possible, I'd suggest auto-rotate at the start, and then automatically stop rotating once any mouse-down or touch-start action happens.  That's more friendly than having another checkbox onscreen.

Also, it would be nice to slow down the auto-rotate quite a bit.  It's a dizzying rotation speed now 😄

**Comment by cx20** [comment]
UI has been added for the following libraries. Also, the rotation speed was made a little slow.

- [x] Three.js
- [x] Babylon.js 
- [ ] Cesium.js
- [x] Grimoire.js
- [x] xeogl
- [ ] Khronos glTF Loader
- [ ] minimal-gltf-loader
- [x] QTEK Model Viewer
- [x] Hilo3d

![image](https://user-images.githubusercontent.com/1833979/33804981-3be2a5c6-ddf4-11e7-96ad-e48dcb00e6d8.png)
