### ISSUE TITLE
how about include playcanvas engine to test?

### ISSUE THREAD

**Issue by sonygod** [cx20/gltf-test#26]
https://github.com/playcanvas/playcanvas-gltf

**Comment by cx20** [comment]
I added the following tests to gltf-test. Other tests are added when normal glTF format is supported.

- Format Tests ( https://github.com/cx20/gltf-test#format-tests )
- All Tests ( https://cx20.github.io/gltf-test/ )

https://github.com/cx20/gltf-test#format-tests
![image](https://user-images.githubusercontent.com/1833979/34910572-77fc634a-f8fb-11e7-92c8-a93fae6a42f7.png)

https://cx20.github.io/gltf-test/
![image](https://user-images.githubusercontent.com/1833979/34910678-952c3dd0-f8fd-11e7-97ac-a6f2087c019b.png)
