### ISSUE TITLE
Extension test in RedCube.js v2.5.4

### ISSUE THREAD

**Issue by Reon90** [cx20/gltf-test#281]
Could you provide a little bit information why RedCube fails Extension test?

**Comment by cx20** [comment]
@Reon90  I'm sorry, the effect of sheen extension is difficult to understand, so it is under verification. I will update my status over the weekend.

**Comment by Reon90** [comment]
@cx20 please check Environment Test rendering.

**Comment by cx20** [comment]
https://github.com/Reon90/redcube/issues/38
