### ISSUE TITLE
Why my image is upside down on some computer?

### ISSUE THREAD

**Issue by PrincessGod** [cx20/gltf-test#34]
On my 15' macbook demo works fine, but on 13' macbook and windows computer are upside down...

Like this
![image](https://user-images.githubusercontent.com/20556748/39674014-491bbabe-5178-11e8-96ac-d51cb7a466d5.png)

Also in jsdo.js
Right
![image](https://user-images.githubusercontent.com/20556748/39674026-71d1a982-5178-11e8-8c6e-fe76eac10030.png)

Wrong
![image](https://user-images.githubusercontent.com/20556748/39674040-906fc9fa-5178-11e8-811b-0f9685b20d7f.png)

Do you have any ideals why? Thanks!

**Comment by cx20** [comment]
@PrincessGod I saw the event at Chrome. If Zoom is set to 110%, it will be displayed upside down.
I do not know the cause. .

**Comment by PrincessGod** [comment]
@cx20  Really strange, not wrong on every computer...

Seems canvas draw thing upside down and left right switched.

**Comment by emackey** [comment]
Not just a zoom change.  Any window resize will trigger this bug.  A window zoom or resize will trigger this line here:

https://github.com/cx20/gltf-test/blob/bcef1b495f99c5d340341f1310ea74736cd47942/examples/czpg/index.js#L139

In `PerspectiveCamera.prototype`, this line is executed:

```
        Matrix4.perspective( this.projMat, this.fov, this.aspect, this.near, this.far );
```

But, `this.fov` is in degrees, not radians.  The `Matrix4` function tries to use the value as radians, and gets confused.  The projection matrix is then flipped over.

**Comment by PrincessGod** [comment]
@emackey  Thanks!
