### ISSUE TITLE
Add Morph Stress Test

### ISSUE THREAD

**Issue by Reon90** [cx20/gltf-test#360]
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MorphStressTest

**Comment by cx20** [comment]
@Reon90 Thank you for teaching me.
I added this model to the [Feature Test Models](https://github.com/cx20/gltf-test#feature-test-models) in [gltf-test](https://github.com/cx20/gltf-test).
![image](https://user-images.githubusercontent.com/1833979/115988651-ac3a3b00-a5f5-11eb-8aa7-3088a419f01c.png)

**Comment by cx20** [comment]
Also, since this model contains multiple animations, I need to investigate how to switch between them.
