### ISSUE TITLE
Add KHR_materials_volume test model

### ISSUE THREAD

**Issue by Reon90** [cx20/gltf-test#371]
https://github.com/KhronosGroup/glTF-Sample-Models/tree/82d3394e95e72e588f1cc2fb84984db27c8adf06/2.0/DragonAttenuation

**Comment by cx20** [comment]
@Reon90 Thanks!
I added this model to the [Extension Test Models](https://github.com/cx20/gltf-test#extension-test-models) in [gltf-test](https://github.com/cx20/gltf-test).
