### ISSUE TITLE
GearboxAssy.gltf does not appear in the center of the screen in Cesium.js v1.47

### ISSUE THREAD

**Issue by cx20** [cx20/gltf-test#38]
I tried to display `GearboxAssy.gltf` with Cesium.js v1.47.
However, it does not seem to be displayed in the center of the screen.

Cesium.js + GearboxAssy.gltf result:
https://cx20.github.io/gltf-test/examples/cesium/index.html?model=GearboxAssy
![image](https://user-images.githubusercontent.com/1833979/42228666-78704314-7f1f-11e8-9691-a71aee37c71a.png)
As Cesium.js v1.46 was displayed in the center of the screen, I think that the specification changed probably.
It is necessary to investigate how to display the glTF model in the center like before.

**Comment by emackey** [comment]
There's been some discussion that the bounding sphere calculation got messed up (possibly by me... oops).  I don't have a link to that issue handy but it might be the cause.

**Comment by emackey** [comment]
This is almost certainly caused by https://github.com/AnalyticalGraphicsInc/cesium/issues/6784 and should be fixed in the next release.

**Comment by cx20** [comment]
@emackey Thank you for clarifying the cause. I would like to confirm the operation again at the next release of Cesium.js.

**Comment by cx20** [comment]
@lilleyse Thank you for fix and checking.
I will do the test again when Cesium.js v1.48 is released and I think that if it does not matter, I will close this Issue.

**Comment by cx20** [comment]
I confirmed that this issue was solved with Cesium.js v1.48.
https://cx20.github.io/gltf-test/examples/cesium/index.html?model=GearboxAssy
![image](https://user-images.githubusercontent.com/1833979/43552355-23507210-9625-11e8-8da6-744f14c8e27d.png)
