### ISSUE TITLE
Add new gltf samples from main repo

### ISSUE THREAD

**Issue by Reon90** [cx20/gltf-test#431]
- Iridescent Dish with Olives
- Specular Test
- Transmission Roughness Test

**Comment by cx20** [comment]
@Reon90 Thank you for pointing out. I have added the following model to [gltf-test](https://github.com/cx20/gltf-test).

https://github.com/cx20/gltf-test#extension-test-models
![image](https://user-images.githubusercontent.com/1833979/126614901-68d51fda-b193-4e9a-a3e4-eed9b93343a6.png)
