### ISSUE TITLE
Add STEP and CUBICSPLINE interpolation tests

### ISSUE THREAD

**Issue by Reon90** [cx20/gltf-test#54]
Models: [interpolation.zip](https://github.com/cx20/gltf-test/files/2722343/interpolation.zip)
Spec: [animation sampler.interpolation](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#animation-samplerinterpolation)

**Comment by cx20** [comment]
@Reon90 Thank you for offering a sample model.
However, [gltf-test](https://github.com/cx20/gltf-test) basically tests the model in the [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models) repository of Khronos Groups.
If there is no problem to licensing, I encourage you to PR in the [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models) repository.

**Comment by emackey** [comment]
Merged: https://github.com/KhronosGroup/glTF-Sample-Models/pull/206

Another one will get merged soon, hopefully today.
