### ISSUE TITLE
ready  add unity test to test list now.

### ISSUE THREAD

**Issue by sonygod** [cx20/gltf-test#64]
https://github.com/sonygod/UnityGLTFTest

**Comment by cx20** [comment]
@sonygod I confirmed that the `UnityGLTF` sample works locally.
![image](https://user-images.githubusercontent.com/1833979/55415379-def4df00-55a7-11e9-911f-052086a0fa00.png)

Since there seems to be almost no problem, I would like to incorporate it into `gltf-test`.

**Comment by cx20** [comment]
I added the `UnityGLTF` sample to the sample list.
https://cx20.github.io/gltf-test/index.html
![image](https://user-images.githubusercontent.com/1833979/55426261-4ec29400-55bf-11e9-9bc8-527211805967.png)
The addition of `gltf-test` to the test result list will be dealt with later.

**Comment by cx20** [comment]
I updated the test results on the top page of `gltf-test`.
![image](https://user-images.githubusercontent.com/1833979/55684615-fc4ef200-5987-11e9-8c23-8533cfe3f51a.png)
