### ISSUE TITLE
Consider the directory structure of gltf-test

### ISSUE THREAD

**Issue by cx20** [cx20/gltf-test#9]
I moved the following discussion to this Issue.
https://github.com/AnalyticalGraphicsInc/cesium/pull/4808#issuecomment-275652301

> I basically want to test using the model obtained from the Khronos official sample site. (https://github.com/KhronosGroup/glTF-Sample-Models)
> However, I have to consider how to structure the folder. I am thinking about the next two plans.
> 
> Plan-1) Version control is done like Three.js
> https://github.com/cx20/gltf-test/tree/r1/sampleModels ... glTF 1.0 (Old version)
> https://github.com/cx20/gltf-test/tree/r1/tutorialModels ... glTF 1.1 (Old version)
> https://github.com/cx20/gltf-test/tree/master/sampleModels ... glTF 2.0 (Latest version)
> https://github.com/cx20/gltf-test/tree/master/tutorialModels ... glTF 2.0 (Latest version)
> 
> Plan-2) Create version folder by category
> https://github.com/cx20/gltf-test/tree/master/sampleModels/1.0 ... glTF 1.0
> https://github.com/cx20/gltf-test/tree/master/sampleModels/2.0 ... glTF 2.0
> https://github.com/cx20/gltf-test/tree/master/tutorialModels/1.1 ... glTF 1.1
> https://github.com/cx20/gltf-test/tree/master/tutorialModels/2.0 ... glTF 2.0

Plan-3) Using github submodule

Please tell me if you have any other good ideas :-)

**Comment by pjcozzi** [comment]
It's your call, but I find that a lot of users get tripped up by submodules.

**Comment by kyasbal-1994** [comment]
I don't recomment submodules also.

**Comment by cx20** [comment]
Thank you both for your advice. Since I am not familiar with git, I need to investigate submodule.
However, I don't think I will use submodule this time.

**Comment by cx20** [comment]
I decided to run Plan 5 tentatively.

Plan-5) Create glTF 2.0 branch
https://github.com/cx20/gltf-test/tree/2.0/sampleModels
https://github.com/cx20/gltf-test/tree/2.0/tutorialModels
